[package]
name = "t9"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
aes = "0.8"
argon2 = "0.5"
blake3 = "1"
blowfish = "0.9"
cbc = { version = "0.1", features = ["alloc"] }
ctr = "0.9"
ed25519-dalek = { version = "2", features = ["rand_core"] }
hmac = "0.12"
jsonwebtoken = "9"
md5 = "0.7"
pbkdf2 = { version = "0.12", features = ["simple"] }
rand = "0.8"
rsa = "0.9"
scrypt = "0.11"
serde = { version = "1", features = ["derive"] }
sha1 = "0.10"
sha2 = { version = "0.10", features = ["oid"] }
x25519-dalek = { version = "2", features = ["static_secrets", "reusable_secrets", "getrandom"] }
