[package]
name = "cargo-cbom"
description = "Generate a CycloneDX 1.7 CBOM for a Cargo workspace"
license.workspace = true
version.workspace=true
edition.workspace=true

[dependencies]
anyhow.workspace = true
clap = { version = "4", features = ["derive"] }
jsonschema = { version = "0.58", default-features = false }
rcbom-analysis.workspace = true
rcbom-facts.workspace = true
rcbom-kb.workspace = true
rcbom-manifest.workspace = true
regex.workspace = true
serde_json.workspace = true
